services:
  group_allocation:
    build: .
    image: group_allocation
    container_name: group_allocation
    ports:
      - "5000:5000"
    volumes:
      - .:/group_app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run_server.py
    tty: true
    stdin_open: true
